# ******************************** VARIABLES DEFINITION*********************************
export
C99_LANG = -std=c99
CPP_03_LANG = -std=c++03
SHARED_LIB_LINK = -shared
STATIC_LIB_LINK = -static
SHARED_LIB_COMPILE = -fPIC
STATIC_LIB_COMPILE =
# ************************END OF VARIABLES DEFINITION SECTION***************************
